admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

app:
    resource: "@AppBundle/Controller/"
    type:     annotation