security:
  encoders:
    UserBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_MODERATOR:       ROLE_USER
    ROLE_ADMIN:           ROLE_MODERATOR

  providers:
    userbundle:
      entity:
        class: UserBundle:User
        property: username

  firewalls:
    main:
      pattern: ^/
      form_login:
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
      logout:
        path:   /wyloguj
        target: /
      anonymous:    true

  access_control:
    - { path: ^/zaloguj$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/zaloz-konto, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetuj, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/ustawienia, role: ROLE_USER }
    - { path: ^/moje, role: ROLE_USER }
    - { path: ^/wyloguj, role: ROLE_USER }
    - { path: ^/admin/, role: ROLE_ADMIN }