<?php

namespace UserBundle\Repository;

/**
 * UserInvoiceDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInvoiceDataRepository extends \Doctrine\ORM\EntityRepository
{
}
