# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.upload_listener:
    class: AppBundle\EventListener\UploadListener
    tags:
      - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }